image: rust:latest

cache:
  paths:
    - target/*

compile:
  stage: build
  script:
    - cargo build --release
  tags:
    - x86_64

test_help:
  stage: test
  script:
    - ./target/release/vct --help
  tags:
    - x86_64

test_version:
  stage: test
  script:
    - ./target/release/vct --version
  tags:
    - x86_64
