[package]
name = "vct"
version = "1.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_derive = "1.0"
serde = "1.0"
toml = "0.5.8"
btui = "0.5.5"
rand = "0.8.4"
